version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - IrukNuj
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: regjsparser
    versions:
    - 0.6.6
    - 0.6.7
    - 0.6.8
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: array-includes
    versions:
    - 3.1.2
  - dependency-name: es-abstract
    versions:
    - 1.17.7
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: graceful-fs
    versions:
    - 4.2.4
    - 4.2.5
